"""create_interview_blueprint_and_session_updates

Revision ID: 0857b1fdd394
Revises: eeefd655f007
Create Date: 2026-07-20 22:59:51.825961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0857b1fdd394'
down_revision: Union[str, None] = 'eeefd655f007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new values to PostgreSQL native enum outside main transaction block
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE sessionstatus ADD VALUE IF NOT EXISTS 'created'")
        op.execute("ALTER TYPE sessionstatus ADD VALUE IF NOT EXISTS 'ready'")
        op.execute("ALTER TYPE sessionstatus ADD VALUE IF NOT EXISTS 'cancelled'")

    op.create_table('interview_blueprints',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('estimated_duration', sa.Integer(), nullable=False),
    sa.Column('blueprint_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_by_profile', sa.String(length=100), nullable=False),
    sa.Column('generated_model', sa.String(length=100), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_blueprints_session_id'), 'interview_blueprints', ['session_id'], unique=True)
    op.add_column('interview_sessions', sa.Column('candidate_profile_id', sa.UUID(), nullable=True))
    op.add_column('interview_sessions', sa.Column('interview_category', sa.Enum('TECHNICAL', 'CODING', 'BEHAVIORAL', 'SYSTEM_DESIGN', name='interviewcategory', native_enum=False), nullable=False))
    op.add_column('interview_sessions', sa.Column('role', sa.Enum('BACKEND', 'FRONTEND', 'FULLSTACK', 'AI_ML', 'DATA_SCIENCE', 'DEVOPS', 'MOBILE', name='interviewrole', native_enum=False), nullable=True))
    op.add_column('interview_sessions', sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', 'ADAPTIVE', name='difficultytype', native_enum=False), nullable=False))
    op.add_column('interview_sessions', sa.Column('duration_minutes', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_interview_sessions_candidate_profile_id'), 'interview_sessions', ['candidate_profile_id'], unique=False)
    op.create_foreign_key(None, 'interview_sessions', 'candidate_profiles', ['candidate_profile_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interview_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_interview_sessions_candidate_profile_id'), table_name='interview_sessions')
    op.drop_column('interview_sessions', 'duration_minutes')
    op.drop_column('interview_sessions', 'difficulty')
    op.drop_column('interview_sessions', 'role')
    op.drop_column('interview_sessions', 'interview_category')
    op.drop_column('interview_sessions', 'candidate_profile_id')
    op.drop_index(op.f('ix_interview_blueprints_session_id'), table_name='interview_blueprints')
    op.drop_table('interview_blueprints')
    # ### end Alembic commands ###
