"""create_interview_turn_analysis

Revision ID: 19dba044cbdc
Revises: e1e152c0fb38
Create Date: 2026-07-21 16:04:46.234221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19dba044cbdc'
down_revision: Union[str, None] = 'e1e152c0fb38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_turn_analyses',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('technical_accuracy', sa.String(length=20), nullable=False),
    sa.Column('depth', sa.String(length=20), nullable=False),
    sa.Column('coverage', sa.String(length=20), nullable=False),
    sa.Column('communication', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('missing_topics', sa.JSON(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('difficulty_level', sa.String(length=20), nullable=False),
    sa.Column('blueprint_section', sa.String(length=100), nullable=False),
    sa.Column('analysis_version', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['interview_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_turn_analyses_message_id'), 'interview_turn_analyses', ['message_id'], unique=False)
    op.add_column('interview_messages', sa.Column('question_type', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_messages', 'question_type')
    op.drop_index(op.f('ix_interview_turn_analyses_message_id'), table_name='interview_turn_analyses')
    op.drop_table('interview_turn_analyses')
    # ### end Alembic commands ###
