"""add_code_execution_infrastructure

Revision ID: 1a091967f098
Revises: 77ce907f0b19
Create Date: 2026-07-24 07:34:06.389479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a091967f098'
down_revision: Union[str, None] = '77ce907f0b19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_submissions',
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('coding_problem_id', sa.UUID(), nullable=False),
    sa.Column('problem_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('submitted_code', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('execution_type', sa.Enum('RUN', 'SUBMIT', name='executiontype'), nullable=False),
    sa.Column('is_final_submission', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('submission_source', sa.Enum('INTERVIEW', 'PRACTICE', 'REPLAY', name='submissionsource'), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('provider_version', sa.String(length=50), nullable=True),
    sa.Column('language_version', sa.String(length=50), nullable=True),
    sa.Column('provider_submission_token', sa.Text(), nullable=True),
    sa.Column('passed_tests', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_tests', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('execution_time_ms', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('memory_kb', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('compile_output', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coding_problem_id'], ['question_bank.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_submissions_coding_problem_id'), 'code_submissions', ['coding_problem_id'], unique=False)
    op.create_index(op.f('ix_code_submissions_session_id'), 'code_submissions', ['session_id'], unique=False)
    op.add_column('coding_problems', sa.Column('driver_templates', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('coding_problems', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coding_problems', 'version')
    op.drop_column('coding_problems', 'driver_templates')
    op.drop_index(op.f('ix_code_submissions_session_id'), table_name='code_submissions')
    op.drop_index(op.f('ix_code_submissions_coding_problem_id'), table_name='code_submissions')
    op.drop_table('code_submissions')
    # ### end Alembic commands ###
