"""create interview domain

Revision ID: 22354c477edb
Revises: 18cf2ef97def
Create Date: 2026-07-17 11:00:52.935472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22354c477edb'
down_revision: Union[str, None] = '18cf2ef97def'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_table('competencies',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competencies_name'), 'competencies', ['name'], unique=True)
    op.create_table('question_bank',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('CODING', 'BEHAVIORAL', 'SYSTEM_DESIGN', 'ML', 'HYBRID', name='interviewtype'), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultytype'), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('question_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_slug'), 'roles', ['slug'], unique=True)
    op.create_table('interview_templates',
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultytype'), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('interview_type', sa.Enum('CODING', 'BEHAVIORAL', 'SYSTEM_DESIGN', 'ML', 'HYBRID', name='interviewtype'), nullable=False),
    sa.Column('resume_required', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('max_questions', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('passing_score', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_templates_company_id'), 'interview_templates', ['company_id'], unique=False)
    op.create_index(op.f('ix_interview_templates_role_id'), 'interview_templates', ['role_id'], unique=False)
    op.create_table('question_competencies',
    sa.Column('question_bank_id', sa.UUID(), nullable=False),
    sa.Column('competency_id', sa.UUID(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_bank_id'], ['question_bank.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_bank_id', 'competency_id', name='uq_question_competencies_question_bank_id_competency_id')
    )
    op.create_index(op.f('ix_question_competencies_competency_id'), 'question_competencies', ['competency_id'], unique=False)
    op.create_index(op.f('ix_question_competencies_question_bank_id'), 'question_competencies', ['question_bank_id'], unique=False)
    op.create_table('question_test_cases',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('input', sa.Text(), nullable=False),
    sa.Column('expected_output', sa.Text(), nullable=False),
    sa.Column('is_sample', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('time_limit_ms', sa.Integer(), server_default=sa.text('2000'), nullable=False),
    sa.Column('memory_limit_kb', sa.Integer(), server_default=sa.text('128000'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question_bank.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_test_cases_question_id'), 'question_test_cases', ['question_id'], unique=False)
    op.create_table('interview_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('resume_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('IDLE', 'IN_PROGRESS', 'EVALUATING', 'COMPLETED', 'FAILED', name='sessionstatus'), nullable=False),
    sa.Column('ended_reason', sa.Enum('COMPLETED', 'USER_LEFT', 'TIMEOUT', 'NETWORK_FAILURE', 'SYSTEM_FAILURE', 'TERMINATED', name='endedreasontype'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('total_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['interview_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_sessions_resume_id'), 'interview_sessions', ['resume_id'], unique=False)
    op.create_index(op.f('ix_interview_sessions_template_id'), 'interview_sessions', ['template_id'], unique=False)
    op.create_index(op.f('ix_interview_sessions_user_id'), 'interview_sessions', ['user_id'], unique=False)
    op.create_table('interview_competency_scores',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('competency_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'competency_id', name='uq_interview_competency_scores_session_id_competency_id')
    )
    op.create_index(op.f('ix_interview_competency_scores_competency_id'), 'interview_competency_scores', ['competency_id'], unique=False)
    op.create_index(op.f('ix_interview_competency_scores_session_id'), 'interview_competency_scores', ['session_id'], unique=False)
    op.create_table('interview_events',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_events_session_id'), 'interview_events', ['session_id'], unique=False)
    op.create_table('interview_questions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('original_question_bank_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('CODING', 'BEHAVIORAL', 'SYSTEM_DESIGN', 'ML', 'HYBRID', name='interviewtype'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('generated_by_ai', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('generation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['original_question_bank_id'], ['question_bank.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_questions_original_question_bank_id'), 'interview_questions', ['original_question_bank_id'], unique=False)
    op.create_index(op.f('ix_interview_questions_session_id'), 'interview_questions', ['session_id'], unique=False)
    op.create_table('interview_responses',
    sa.Column('interview_question_id', sa.UUID(), nullable=False),
    sa.Column('response_type', sa.Enum('VOICE', 'TEXT', 'CODE', name='responsetype'), nullable=False),
    sa.Column('response_content', sa.Text(), nullable=False),
    sa.Column('audio_url', sa.String(length=2048), nullable=True),
    sa.Column('programming_language', sa.String(length=50), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('transcript_confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_question_id'], ['interview_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_responses_interview_question_id'), 'interview_responses', ['interview_question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_responses_interview_question_id'), table_name='interview_responses')
    op.drop_table('interview_responses')
    op.drop_index(op.f('ix_interview_questions_session_id'), table_name='interview_questions')
    op.drop_index(op.f('ix_interview_questions_original_question_bank_id'), table_name='interview_questions')
    op.drop_table('interview_questions')
    op.drop_index(op.f('ix_interview_events_session_id'), table_name='interview_events')
    op.drop_table('interview_events')
    op.drop_index(op.f('ix_interview_competency_scores_session_id'), table_name='interview_competency_scores')
    op.drop_index(op.f('ix_interview_competency_scores_competency_id'), table_name='interview_competency_scores')
    op.drop_table('interview_competency_scores')
    op.drop_index(op.f('ix_interview_sessions_user_id'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_template_id'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_resume_id'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_index(op.f('ix_question_test_cases_question_id'), table_name='question_test_cases')
    op.drop_table('question_test_cases')
    op.drop_index(op.f('ix_question_competencies_question_bank_id'), table_name='question_competencies')
    op.drop_index(op.f('ix_question_competencies_competency_id'), table_name='question_competencies')
    op.drop_table('question_competencies')
    op.drop_index(op.f('ix_interview_templates_role_id'), table_name='interview_templates')
    op.drop_index(op.f('ix_interview_templates_company_id'), table_name='interview_templates')
    op.drop_table('interview_templates')
    op.drop_index(op.f('ix_roles_slug'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('question_bank')
    op.drop_index(op.f('ix_competencies_name'), table_name='competencies')
    op.drop_table('competencies')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
