"""add_resume_metadata_columns

Revision ID: 402b9840e5de
Revises: 22354c477edb
Create Date: 2026-07-18 16:14:55.278492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '402b9840e5de'
down_revision: Union[str, None] = '22354c477edb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('original_filename', sa.String(length=255), nullable=False))
    op.add_column('resumes', sa.Column('mime_type', sa.String(length=100), nullable=False))
    op.add_column('resumes', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('resumes', sa.Column('status', sa.String(length=50), server_default=sa.text("'uploaded'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'status')
    op.drop_column('resumes', 'file_size')
    op.drop_column('resumes', 'mime_type')
    op.drop_column('resumes', 'original_filename')
    # ### end Alembic commands ###
