"""create_coding_problem_and_language_template_models

Revision ID: 77ce907f0b19
Revises: c3cd880fc417
Create Date: 2026-07-23 18:52:06.475333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77ce907f0b19'
down_revision: Union[str, None] = 'c3cd880fc417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('boilerplate_wrapper', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language')
    )
    op.create_table('coding_problems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('function_signatures', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('optimal_solutions', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('optimal_time_complexity', sa.String(length=50), nullable=False),
    sa.Column('optimal_space_complexity', sa.String(length=50), nullable=False),
    sa.Column('hints', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('follow_ups', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('recommended_languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('learning_objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('companies', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.ForeignKeyConstraint(['id'], ['question_bank.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coding_problems')
    op.drop_table('language_templates')
    # ### end Alembic commands ###
