"""add_interview_messages_and_state

Revision ID: e1e152c0fb38
Revises: c6964af27375
Create Date: 2026-07-21 01:12:52.805628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1e152c0fb38'
down_revision: Union[str, None] = 'c6964af27375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_messages_session_id'), 'interview_messages', ['session_id'], unique=False)
    op.add_column('interview_sessions', sa.Column('interview_state', sa.Enum('READY', 'GREETING', 'INTRODUCTION', 'IN_PROGRESS', 'CLOSING', 'COMPLETED', name='interviewstate', native_enum=False), server_default='READY', nullable=False))
    op.add_column('interview_sessions', sa.Column('current_section_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'current_section_index')
    op.drop_column('interview_sessions', 'interview_state')
    op.drop_index(op.f('ix_interview_messages_session_id'), table_name='interview_messages')
    op.drop_table('interview_messages')
    # ### end Alembic commands ###
