import React, { useEffect } from 'react';
import { useUIStore } from '@/store/useUIStore';
import { DashboardLayout } from '@/components/layouts/DashboardLayout';
import { Timeline, TimelineItem } from '@/components/shared/Timeline';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Sparkles, Map } from 'lucide-react';

const ROADMAP_STEPS: TimelineItem[] = [
  { id: '1', title: 'Master Core Sorting & Arrays', description: 'Solved 12 array and 8 hash map problems. Key progress: 95% pass rate.', date: 'Completed Jul 12', status: 'completed' },
  { id: '2', title: 'System Design: Distributed Data Stores', description: 'Learn cache partition strategies, Redis clusters, and Master-replica setups.', date: 'Completed Jul 14', status: 'completed' },
  { id: '3', title: 'Concurrences & Thread Synchronizations', description: 'Implement rate limiters under concurrent traffic spikes. Target: solve 4 locking challenges.', date: 'In progress', status: 'current' },
  { id: '4', title: 'Behavioral prep: Conflicts & Scope Prunings', description: 'Review 3 leadership scenarios. Build structured STAR summaries.', date: 'Upcoming', status: 'upcoming' },
  { id: '5', title: 'Vercel Mock Simulation Run', description: 'Simulated full-loop technical and managerial interview session.', date: 'Upcoming', status: 'upcoming' },
];

export default function Roadmap() {
  const { setBreadcrumbs } = useUIStore();

  useEffect(() => {
    setBreadcrumbs(['Dashboard', 'AI Learning Roadmap']);
  }, [setBreadcrumbs]);

  return (
    <DashboardLayout>
      <div className="max-w-3xl mx-auto space-y-6 select-none">
        <div className="flex items-center gap-3 border-b border-border pb-6">
          <div className="p-3 rounded-full bg-[#4285F4] text-white shrink-0 shadow-sm">
            <Map className="h-5 w-5" />
          </div>
          <div>
            <h2 className="text-3xl font-extrabold tracking-tight">Learning Roadmap</h2>
            <p className="text-muted-foreground text-sm mt-0.5 select-text">
              Personalized prep pathway generated by analyzing your mock session evaluations.
            </p>
          </div>
        </div>

        {/* AI Insight banner */}
        <div className="p-4 bg-gradient-to-r from-violet-600/5 to-indigo-600/5 border border-violet-500/10 rounded-2xl text-xs flex items-start gap-3">
          <Sparkles className="h-5 w-5 text-violet-500 shrink-0 mt-0.5 animate-pulse" />
          <div className="space-y-1 select-text">
            <p className="font-semibold text-violet-700 dark:text-violet-300">AI Adaptation Active</p>
            <p className="text-muted-foreground leading-relaxed">
              Your weak scores on **Concurrency** have automatically inserted a priority learning node: *Concurrences & Thread Synchronizations*. Clear this node to unlock Vercel's simulation run.
            </p>
          </div>
        </div>

        <Card className="hover:border-foreground/15 transition-all duration-300 rounded-2xl bg-card/60 backdrop-blur-md border border-border/50 shadow-sm">
          <CardHeader className="p-6">
            <CardTitle className="text-base font-bold">Preparation Progress</CardTitle>
            <CardDescription className="text-xs">Follow this checklist to reach ready status.</CardDescription>
          </CardHeader>
          <CardContent className="p-6 pt-0">
            <Timeline items={ROADMAP_STEPS} />
          </CardContent>
        </Card>
      </div>
    </DashboardLayout>
  );
}
export { Roadmap };
